### ISSUE TITLE
__javaclass__ AttributeError with with jPype 1.2.0 and jtds Driver

### ISSUE THREAD

**Issue by theglob** [baztian/jaydebeapi#178]
Hi,

so the previously fixed Problem (
[https://github.com/baztian/jaydebeapi/issues/131](url)) seems to be there again with jPype version 1.2.0

I am using:

Python 3.6
Driver: net.sourceforge.jtds.jdbc.Driver
Version: jtds-1.3.1

Everything worked fine with jpype1-0.6.3 until i recently encountered an Exception associated with jpype 
[https://github.com/jpype-project/jpype/issues/290#issuecomment-746678533](url). This issue could be solved by manually checking running JVMs. However i was advised to not use the fix and instead upgrade to 1.2.0.

After upgrading i encountered the old Attributeerror caused by jaydebeapi:

 File "/database.py", line 183, in connect
    engine = jaydebeapi.connect(driver_name, conn_str, props, jar_path)
  File "/Users/miroconzelmann/opt/anaconda3/envs/testenv/lib/python3.6/site-packages/jaydebeapi/__init__.py", line 381, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/opt/anaconda3/envs/testenv/lib/python3.6/site-packages/jaydebeapi/__init__.py", line 182, in _jdbc_connect_jpype
    for i in types.__javaclass__.getClassFields():
AttributeError: type object 'java.sql.Types' has no attribute '__javaclass__'

**Comment by Thrameos** [comment]
What version of jaybedeapi?

**Comment by theglob** [comment]
JayDeBeApi 1.1.1

**Comment by Thrameos** [comment]
Okay I was going to say that error looks a lot like old versions.   JayDeBeAPI was accessing private fields that were removed in later versions of JPype, so you have to use the later version which is aware of the changes.
